# Tests on linux arm and arm64, no gpu.
# https://discourse.julialang.org/t/testing-on-arm-with-drone-ci/25871/2

kind: pipeline
name: linux-arm-1.4

platform:
 os: linux
 arch: arm

steps:
- name: build
  image: julia:1.4
  commands:
     - uname -a
     - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

---

kind: pipeline
name: linux-arm64-1.4

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1.4
  commands:
      - uname -a
      - julia --project=. -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

